### ISSUE TITLE
Add chasm

### ISSUE THREAD

**Issue by Courtsilius** [Nocte-Clara/nekomancer#8]
Player should be able to drop down a chasm and then be teleported back on to the playable area

**Comment by Bashiralh** [comment]
Hi  @Courtsilius 

I'm currently working on completing this issue. Testing this feature is a bit challenging using only mouse clicks for player movement.

Would it be possible to implement keyboard movement controls using the WASD keys instead of just the left mouse click? This change would make testing and development much smoother for this and future tasks.

**Comment by Courtsilius** [comment]
> Hi @Courtsilius
> 
> I'm currently working on completing this issue. Testing this feature is a bit challenging using only mouse clicks for player movement.
> 
> Would it be possible to implement keyboard movement controls using the WASD keys instead of just the left mouse click? This change would make testing and development much smoother for this and future tasks.

That is definitely something that will be worked on soon, I can try and see if I can get something rudamentary working shortly, but just wasnt as important for the basic prototype as some of the other items on the list.

**Comment by Courtsilius** [comment]
@Bashiralh the new player controller is in #16 , so it should be in the prototype soon, but you can already in theory just use that branch for testing
